### ISSUE TITLE
PentClass

### ISSUE THREAD

**Issue by chilland** [ahalterman/phoxy#10]
Hello. Currently `phoxy` uses `QuadClass` in the column names, however it is my understanding that `PentaClass` is the preferred term due to the addition of `0`.

**Comment by ahalterman** [comment]
You're right. The use of QuadClass was to avoid breaking a bunch of my old code and because I wasn't sure if PentaClass was going to catch on. But I agree that it should be changed.

**Comment by johnb30** [comment]
:+1: to this.

**Comment by ahalterman** [comment]
There's a PR that should fix it (and fix a serious bug that prevented the download of Phoenix in general. 
![image](https://cloud.githubusercontent.com/assets/4378727/8379511/8921c6de-1bee-11e5-8b54-f19b37b9665d.png)

If one of you try it out and it works for you, I'll merge the PR.
