### ISSUE TITLE
Trouble downloading Phoenix — probably a bug in dw_file function

### ISSUE THREAD

**Issue by roveo** [ahalterman/phoxy#12]
So download_phoenix fails.

The problem is in this piece code (currently line 41):

``` R
filename <- gsub(baseurl, "", link)
```

`filename` value in this case will be for example `/path/to/destpath/https://s3.amazonaws.com/openeventdata/current/events.full.20140410.txt.zip` which necessarily raises an exception.

I'm afraid the problem is that `baseurl` as a regexp doesn't match itself as a string. I'll try to provide a pull request with a fix in the following days.

**Comment by ahalterman** [comment]
Hi Roveo. You're right, the regex on the URL is a pretty clunky way to do it. I just realized I had a stale PR waiting to be merged to master. I just merged it in. You might want to see if that clears up the problem, and if not, PRs are very, very welcome!

**Comment by roveo** [comment]
Hi! Looks like it does fix the problem.

I've been also working on some refactoring for this file, will create a PR in a moment, please take a look. The main idea is that when you extract filename from URL it shouldn't depend on any hardcoded base URLs (in case they change again).
- `get_links` is now the only place that logically needs `phoenix_version` parameter, all the other functions just pass it there
- `file_dw` doesn't depend on any particular URL or filename scheme, just must have `.zip` in the end
- the code is now less dependent on the correct user input, like it automatically adds trailing `/` to paths and `v` in the beginning of `phoenix_version` if it's not there
- now it doesn't directly import any packages into the global namespace
- generally it uses standard packages instead of external (like `RCurl`)
